### ISSUE TITLE
Rethink changelog and documentation deliverables

### ISSUE THREAD

**Issue by edwinvdgraaf** [DigitPaint/roger#16]
The generation of documentation, TOC and changelog that are delivered are still depended on copy-paste from earlier projects. To ease the process, we should reconsider how we work with this. As an artefact of earlier mockup versions we still rely on injecting the changelog, we could leverage Tilt here for example. Currently we lack syntax highlighting for example. This is just an example however, I am interested in the problems people experience while using roger in their workflow. 

For the moment I will focus my effort on creating a generate command for these _doc files, however feedback is very appreciated! 

- [ ] Make packages available via download #18 
- [ ] create generate command for _doc template
- [ ] Syntax highlighting
- [ ] TOC
- [ ] html diffs?

**Comment by edwinvdgraaf** [comment]
Another often requested feature is to be able to download the package directly from the reference HTML. Also versioning comes to mind.

**Comment by flurin** [comment]
I don't believe in generators for this; this should be automated in middleware / processor steps so they'll ALWAYS be there

**Comment by flurin** [comment]
Made issue #18 for download of packages.

**Comment by edwinvdgraaf** [comment]
Closing this issue in favor of some smaller ones.

For syntax highlgihting there is now https://github.com/DigitPaint/roger_better_markdown
