### ISSUE TITLE
Add ability to add layouts and partial via plugins

### ISSUE THREAD

**Issue by edwinvdgraaf** [DigitPaint/roger#23]
While this is already possible in the Mockupfile (see below), it should be able to append paths to this array in plugins.

```
mockup.project.partial_path = [mockup.project.path + "partials", mockup.project.path + "libs/website-shared/partials"]
```

**Comment by flurin** [comment]
It's a plain array. Use `mockup.project.partial_path << "my new path"`

**Comment by edwinvdgraaf** [comment]
Great. :+1:
