### ISSUE TITLE
Add NPM/Bower dependencies check

### ISSUE THREAD

**Issue by edwinvdgraaf** [DigitPaint/roger#44]
Allow some sort of check for dependencies during start like bundler does.

**Comment by flurin** [comment]
Bower has the option to output json so that should be consumable `bower list --json` says "missing" if a dependency is missing.

NPM I'm not sure but it should have an option like that as well.

Question is: should this be a plugin? IMHO: yes.

**Comment by edwinvdgraaf** [comment]
I'm not sure about yet another plugin, finding the setup time for each plugin to by quite
costly already. However, it's really specific functionality which doesn't necessarily belongs
inside roger.

**Comment by edwinvdgraaf** [comment]
Closing this one.

Bower seems fading, npm is still a strange, but solution should be found outside roger. Think shrinkwrap, build from clean environments etc.
